package manyCustomException;

public class Test {
	public static void main(String[] args) {
		
	}

	
	
	public static void validate() {
		//try {
		int num1 = 8;
		int num2 = 2;
		int res = num1/num2;
		int array[] = new int[5];
		System.out.println(res);
		String name = "";
		System.out.println(name);
		//}catch(Exception e) {
			
		//}
	}
}
